# Streamlit Secrets Configuration
# Copy this to .streamlit/secrets.toml for deployment

[general]
GEMINI_API_KEY = "your_free_gemini_api_key_here"
SECRET_KEY = "your_secret_key_here"

[database]
DATABASE_URL = "sqlite:///resumeai.db"

[auth]
JWT_SECRET = "your_jwt_secret_here"

[branding]
APP_NAME = "AI Resume Analyzer Pro"
COMPANY_NAME = "Syed Ali Hashmi"
SUPPORT_EMAIL = "support@resumeai.com"